name: Update GitHub Profile Metrics

on:
  workflow_dispatch:

  schedule:
    - cron: "17 */6 * * *"

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate profile metrics
        uses: mjun0812/github-metrics@v5
        with:
          user: Nina-99
          token: ${{ secrets.GITHUB_TOKEN }}
          template: classic

          output_dir: ./metrics/
          output_action: commit
          output_condition: data-changed
          committer_branch: main
          committer_message: "chore: update GitHub profile metrics"

          plugin_header: true
          plugin_languages: true
          plugin_stars: true
          plugin_activity: true
